Repository ithacaxyz/op-rs, pull requests merged in 2024-10, with the labels that each got.

#101 chore: rm kona-providers, update dependencies
  Cargo.lock
  Cargo.toml
  Justfile
  README.md
  bin/hera/src/main.rs
  bin/op-rs/src/main.rs
  crates/kona-providers/src/lib.rs
  crates/net/Cargo.toml
  crates/net/src/driver.rs
  crates/net/src/gossip/handler.rs
  crates/net/src/lib.rs
  crates/net/src/types/envelope.rs
  crates/net/src/types/mod.rs
  crates/net/src/types/payload.rs
  crates/providers-local/Cargo.toml
  crates/providers-local/src/blob_provider.rs
  crates/providers-local/src/chain_provider.rs
  crates/providers-local/src/lib.rs
  crates/rollup/Cargo.toml
  crates/rollup/src/driver/context/exex.rs
  crates/rollup/src/driver/context/mod.rs
  crates/rollup/src/driver/context/standalone.rs
  crates/rollup/src/driver/cursor.rs
  crates/rollup/src/driver/mod.rs
  crates/rollup/src/lib.rs
  crates/rollup/src/pipeline.rs
  crates/rollup/src/validator.rs
  crates/ser/Cargo.toml
  crates/ser/src/lib.rs
Labels: A-dependencies

#35 feat(rpc): Setup RPC Crate
  Cargo.lock
  Cargo.toml
  bin/hera/Cargo.toml
  bin/op-rs/Cargo.toml
  crates/net/Cargo.toml
  crates/rollup/Cargo.toml
  crates/rpc/Cargo.toml
  crates/rpc/src/lib.rs
  crates/rpc/src/rollup.rs
  crates/rpc/src/sequencer.rs
  crates/ser/Cargo.toml
Labels: A-rpc

#102 feat(rpc): add engine api abstraction, rm `AttributesValidator`
  Cargo.lock
  Cargo.toml
  crates/rollup/Cargo.toml
  crates/rollup/src/cli.rs
  crates/rollup/src/driver/mod.rs
  crates/rollup/src/engine.rs
  crates/rollup/src/lib.rs
  crates/rollup/src/validator.rs
Labels: A-rpc, A-rollup

#105 feat: cleanup + update deps + rm kona-primitives
  .github/workflows/lint.yml
  Cargo.lock
  Cargo.toml
  bin/op-rs/src/main.rs
  clippy.toml
  crates/providers-local/Cargo.toml
  crates/providers-local/src/blob_provider.rs
  crates/providers-local/src/chain_provider.rs
  crates/rollup/Cargo.toml
  crates/rollup/src/driver/context/exex.rs
  crates/rollup/src/driver/context/mod.rs
  crates/rollup/src/driver/context/standalone.rs
  crates/rollup/src/driver/mod.rs
  crates/rollup/src/engine.rs
  crates/rollup/src/validator.rs
Labels: A-dependencies

#111 chore: Versioned Kona
  Cargo.lock
  Cargo.toml
Labels: C-enhancement, A-dependencies
